spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:../db/ai2code-database.sqlite
    hikari:
      max-lifetime: 0
      maximum-pool-size: 1
  config:
    activate:
      on-profile: sqlite
  sql:
    init:
      mode: never
      platform: sqlite
  web.resources.static-locations: file:./app/
cds:
  odata-v4:
    endpoint:
      path: /api
    lazy-i18n:
      enabled: true
  data-source.auto-config.enabled: false
